type CommandResponse {
  code: Int
  message: String
}

type VehicleGenerationStatus {
  isGenerating: Boolean!
  status: String!
}

type Vehicle {
  type: String!
  powerSource: String!
  hp: Int!
  year: Int!
  topSpeed: Int!
}

type VehicleGeneratedEvent {
  timestamp: String!
  data: Vehicle!
}

extend type Query {
  VehicleMngGenerationStatus: VehicleGenerationStatus
}

extend type Mutation {
  VehicleMngStartGeneration: CommandResponse
  VehicleMngStopGeneration: CommandResponse
}

extend type Subscription {
  VehicleMngVehicleGenerated: VehicleGeneratedEvent
}
